labels:
  app-group: jarvis
  language: rust

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: rust:1.51-alpine3.13
    commands:
    - cargo --version
    - cargo test
    - cargo build --release