labels:
  app-group: jarvis
  language: rust

version:
  semver:
    major: 0
    minor: 1

stages:
  bake:
    image: extensions/docker:stable
    action: build
    container: jarvis-lib-builder
    repositories:
    - jsalverda

  push-to-docker-hub:
    image: extensions/docker:stable
    action: push
    container: jarvis-lib-builder
    repositories:
    - jsalverda
    tags:
    - latest

  tag-revision:
    image: alpine:3.13
    commands:
    - apk add git
    - git tag ${ESTAFETTE_BUILD_VERSION}
    - git push origin ${ESTAFETTE_BUILD_VERSION}